export const UPDATE_PLAYER = 'UPDATE_PLAYER';
export const SET_USERNAME = 'SET_USERNAME';
export const RETRIEVE_PLAYER = 'RETRIEVE_PLAYER';
export const ADD_GAME_TO_LIST = 'ADD_GAME_TO_LIST';
export const UPDATE_GAME_LIST = 'UPDATE_GAME_LIST';
export const REMOVE_GAME_FROM_LIST = 'REMOVE_GAME_FROM_LIST';
export const CLEAR_PLAYER = 'CLEAR_PLAYER';
